Repository Deci-AI/super-gradients, pull requests merged in 2022-02, with the labels that each got.

#121 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: size/M

#127 Feature/dle 1005 updated efficientnet recipe
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_efficientnet_train_params.yaml
Labels: size/M

#128 Added DropPath to ResNet, retrained, achieved 79.47 top-1
  src/super_gradients/recipes/imagenet_resnet50.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_resnet50_train_params.yaml
  src/super_gradients/training/datasets/segmentation_datasets/coco_segmentation.py
  src/super_gradients/training/models/classification_models/resnet.py
  src/super_gradients/training/pretrained_models.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/M

#125 Added RegSeg to codebase
  src/super_gradients/recipes/cityscapes_regseg48.yaml
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/segmentation_models/regseg.py
  src/super_gradients/training/pretrained_models.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/XL

#126 fix add_image img_tensor arg
  src/super_gradients/common/sg_loggers/base_sg_logger.py
Labels: size/XS

#134 Fixed ElasticSearch version to 7.15.2 to prevent tests of loggers from failing
  requirements.txt
Labels: size/XS

#131 Quickstart detection and readme update
  README.md
  src/super_gradients/examples/SG_quickstart_detection.ipynb
  src/super_gradients/examples/quickstart.ipynb
Labels: size/XXL
