Repository Deci-AI/super-gradients, pull requests merged in 2022-06, with the labels that each got.

#185 Feature/sg 109 beit architecture
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/classification_models/beit.py
  src/super_gradients/training/pretrained_models.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#213 Feature/sg 128 kd recipe resnet50
  src/super_gradients/__init__.py
  src/super_gradients/examples/train_from_kd_recipe_example/__init__.py
  src/super_gradients/examples/train_from_kd_recipe_example/train_from_kd_recipe.py
  src/super_gradients/recipes/imagenet_resnet50_kd.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_resnet50_kd_train_params.yaml
  src/super_gradients/training/__init__.py
  src/super_gradients/training/kd_model/__init__.py
  src/super_gradients/training/kd_trainer.py
  src/super_gradients/training/losses/__init__.py
  src/super_gradients/training/losses/all_losses.py
  src/super_gradients/training/pretrained_models.py
  src/super_gradients/training/trainer.py
  src/super_gradients/training/utils/kd_model_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#214 Feature/sg 000 cifar10 beit url
  src/super_gradients/training/pretrained_models.py
Labels: size/XS

#215 bug fixed
  src/super_gradients/training/utils/checkpoint_utils.py
Labels: size/XS

#216 Widen deci-lab-client dependency range
  requirements.txt
Labels: size/XS

#222 fix: Get rid of steps
  src/super_gradients/training/utils/ssd_utils.py
Labels: size/S

#221 refactor: Readable scale
  src/super_gradients/training/losses/ssd_loss.py
Labels: size/XS

#219 fix: Get people back their own class
  src/super_gradients/training/losses/ssd_loss.py
  src/super_gradients/training/utils/ssd_utils.py
Labels: size/XS

#208 detection transforms and their utils added
  src/super_gradients/training/transforms/transforms.py
  src/super_gradients/training/utils/detection_utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/detection_targets_format_transform_test.py
Labels: size/XL

#225 LAB-3539 Use direct import in mobilenetv2
  src/super_gradients/training/models/classification_models/mobilenetv2.py
  src/super_gradients/training/models/detection_models/yolov5_base.py
  src/super_gradients/training/utils/detection_utils.py
  src/super_gradients/training/utils/utils.py
Labels: size/L

#201 Feature/sg 39 improve train valid format
  requirements.txt
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/sg_model_utils.py
Labels: size/L

#228 Update README.md
  README.md
Labels: size/XS

#229 fix broken links
  README.md
Labels: size/XS

#226 training switch cb added
  src/super_gradients/training/utils/callbacks.py
Labels: size/M

#209 Feature/sg 13 detection metrics update
  src/super_gradients/training/metrics/detection_metrics.py
Labels: size/M

#223 Feature/sg 13 coco dataset yolox
  src/super_gradients/recipes/dataset_params/coco_detection_yolox_dataset_params.yaml
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/datasets_utils.py
  src/super_gradients/training/datasets/detection_datasets/coco_detection_yolox.py
  src/super_gradients/training/datasets/samplers/infinite_sampler.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/transforms/transforms.py
  src/super_gradients/training/utils/distributed_training_utils.py
Labels: size/XL
