Repository Deci-AI/super-gradients, pull requests merged in 2022-11, with the labels that each got.

#441 add list resolvers to OmegaConf to get items from list
  src/super_gradients/common/environment/env_helpers.py
  tests/unit_tests/hydra_resolvers_test.py
Labels: size/S

#435 when env sanity check fails - print error
  src/super_gradients/sanity_check/env_sanity_check.py
Labels: size/XS

#434 add deci requirements to ensure compatibility
  .circleci/config.yml
  requirements.pro.txt
  requirements.txt
  setup.py
  src/super_gradients/sanity_check/env_sanity_check.py
Labels: size/M

#401 Custom UNet architecture
  src/super_gradients/common/factories/__init__.py
  src/super_gradients/common/factories/context_modules_factory.py
  src/super_gradients/common/factories/optimizers_type_factory.py
  src/super_gradients/common/factories/type_factory.py
  src/super_gradients/common/object_names.py
  src/super_gradients/modules/repvgg_block.py
  src/super_gradients/recipes/arch_params/unet_default_arch_params.yaml
  src/super_gradients/training/models/__init__.py
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/arch_params_factory.py
  src/super_gradients/training/models/segmentation_models/context_modules.py
  src/super_gradients/training/models/segmentation_models/ppliteseg.py
  src/super_gradients/training/models/segmentation_models/segmentation_module.py
  src/super_gradients/training/models/segmentation_models/stdc.py
  src/super_gradients/training/models/segmentation_models/unet/__init__.py
  src/super_gradients/training/models/segmentation_models/unet/unet.py
  src/super_gradients/training/models/segmentation_models/unet/unet_decoder.py
  src/super_gradients/training/models/segmentation_models/unet/unet_encoder.py
Labels: size/XXL

#447 wheel>=0.38.0
  requirements.txt
Labels: size/XS

#449 docs: Update registry readme
  src/super_gradients/common/registry/README.md
Labels: size/XS

#448 Apply black on trainer
  src/super_gradients/training/sg_trainer/sg_trainer.py
Labels: size/XL

#452 Bug/sg 318 default optimizer params not taken with zero wd on bn and bias
  src/super_gradients/training/params.py
  src/super_gradients/training/utils/optimizer_utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/__init__.py
  tests/unit_tests/optimizer_params_override_test.py
Labels: size/L

#450 Feature/sg 321 ddp sampler handling for external dataloaders
  src/super_gradients/training/dataloaders/dataloaders.py
  tests/unit_tests/datalaoder_factory_test.py
Labels: size/M

#440 Feature-280/ throw error when using sequential sampler with DDP
  src/super_gradients/training/sg_trainer/sg_trainer.py
Labels: size/S

#446 Adding some documentation on how to define a custom metric
  src/super_gradients/common/registry/README.md
Labels: size/M

#453 ckpt_root_dir bug fixed
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
Labels: size/XS

#444 Fix for logs not written in the experiment dir
  src/super_gradients/common/abstractions/abstract_logger.py
  src/super_gradients/common/auto_logging/auto_logger.py
  src/super_gradients/common/auto_logging/auto_logging_conf.json
  src/super_gradients/common/sg_loggers/base_sg_logger.py
  src/super_gradients/recipes/training_hyperparams/default_train_params.yaml
  src/super_gradients/training/params.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
  tests/unit_tests/train_logging_test.py
Labels: size/L

#455 Bug/sg 301 calling train twice crashes
  src/super_gradients/training/sg_trainer/sg_trainer.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/__init__.py
  tests/unit_tests/double_training_test.py
Labels: size/M

#457 Apply black to detection datasets and transforms
  src/super_gradients/training/datasets/__init__.py
  src/super_gradients/training/datasets/datasets_conf.py
  src/super_gradients/training/datasets/detection_datasets/__init__.py
  src/super_gradients/training/datasets/detection_datasets/coco_detection.py
  src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
  src/super_gradients/training/datasets/detection_datasets/pascal_voc_detection.py
  src/super_gradients/training/transforms/all_transforms.py
  src/super_gradients/training/transforms/transforms.py
Labels: size/XL

#463 Fix drop_last support in BatchSampler
  src/super_gradients/training/dataloaders/dataloaders.py
Labels: size/XS

#459 Fix setup of DDP in eval_from_recipe
  src/super_gradients/training/sg_trainer/sg_trainer.py
Labels: size/XS

#427 Feature/alg 743 new detection base
  src/super_gradients/common/factories/__init__.py
  src/super_gradients/common/factories/detection_modules_factory.py
  src/super_gradients/common/registry/__init__.py
  src/super_gradients/common/registry/registry.py
  src/super_gradients/modules/detection_modules.py
  src/super_gradients/training/models/detection_models/customizable_detector.py
Labels: size/L

#430 Feature/SG 344 - CSPResNet
  src/super_gradients/modules/__init__.py
  src/super_gradients/modules/se_blocks.py
  src/super_gradients/recipes/arch_params/csp_resnet_arch_params.yaml
  src/super_gradients/recipes/arch_params/csp_resnet_l_arch_params.yaml
  src/super_gradients/recipes/arch_params/csp_resnet_m_arch_params.yaml
  src/super_gradients/recipes/arch_params/csp_resnet_s_arch_params.yaml
  src/super_gradients/recipes/arch_params/csp_resnet_x_arch_params.yaml
  src/super_gradients/training/models/detection_models/csp_resnet.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/ppyoloe_unit_test.py
Labels: size/L

#414 Feature/sg 236 integrate clear ml
  src/super_gradients/common/sg_loggers/__init__.py
  src/super_gradients/common/sg_loggers/clearml_sg_logger.py
  src/super_gradients/training/utils/callbacks/all_callbacks.py
Labels: size/L

#468 Bug/sg 399 external checkpoints fix
  src/super_gradients/training/sg_trainer/sg_trainer.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/__init__.py
  tests/unit_tests/resume_training_test.py
Labels: size/L

#469 classes list through kwargs in coco
  src/super_gradients/training/datasets/detection_datasets/coco_detection.py
Labels: size/XS

#464 Apply black on some checkpoint related folders (REQUIRED FOR BUG FIX)
  src/super_gradients/common/environment/env_helpers.py
  src/super_gradients/training/utils/checkpoint_utils.py
  src/super_gradients/training/utils/distributed_training_utils.py
Labels: size/L

#458 update readme: change All Computer Vision Models - Pretrained Checkpo…
  README.md
Labels: size/XS

#466 Fix: pass extra args to subprocesses in ddp
  src/super_gradients/common/environment/env_helpers.py
  src/super_gradients/common/environment/environment_config.py
  src/super_gradients/training/utils/distributed_training_utils.py
Labels: size/XS

#470 Update lab version requirement
  requirements.pro.txt
Labels: size/XS

#467 Fix: get_ckpt_local_path not working when no default "checkpoints" folder
  src/super_gradients/training/utils/checkpoint_utils.py
Labels: size/S

#475 Feature/sg 000 clean start prints
  src/super_gradients/common/sg_loggers/clearml_sg_logger.py
  src/super_gradients/training/dataloaders/dataloaders.py
  src/super_gradients/training/training_hyperparams/training_hyperparams.py
  src/super_gradients/training/utils/hydra_utils.py
  src/super_gradients/training/utils/quantization_utils.py
  tests/unit_tests/ppyoloe_unit_test.py
Labels: size/L

#471 Feature/sg 415 add registry callback and transform
  src/super_gradients/common/registry/README.md
  src/super_gradients/common/registry/registry.py
Labels: size/XS

#473 Add doc for clearML integration
  README.md
  src/super_gradients/common/sg_loggers/clearml_sg_logger.py
  src/super_gradients/common/sg_loggers/deci_platform_sg_logger.py
  src/super_gradients/examples/deci_platform_logger_example/deci_platform_logger_example.py
  src/super_gradients/examples/loggers_examples/__init__.py
  src/super_gradients/examples/loggers_examples/clearml_logger_example.py
  src/super_gradients/examples/loggers_examples/deci_platform_logger_example.py
Labels: size/L

#479 Bugfix- calling train after test
  src/super_gradients/training/sg_trainer/sg_trainer.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/__init__.py
  tests/unit_tests/train_after_test_test.py
Labels: size/M

#460 Feature/sg 195 bbox formats
  src/super_gradients/common/factories/__init__.py
  src/super_gradients/common/factories/bbox_format_factory.py
  src/super_gradients/training/utils/bbox_formats/__init__.py
  src/super_gradients/training/utils/bbox_formats/bbox_format.py
  src/super_gradients/training/utils/bbox_formats/cxcywh.py
  src/super_gradients/training/utils/bbox_formats/xywh.py
  src/super_gradients/training/utils/bbox_formats/xyxy.py
  src/super_gradients/training/utils/bbox_formats/yxyx.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/bbox_formats_test.py
Labels: size/XL

#474 Mute env_sanity_check for subprocess in DDP
  src/super_gradients/common/environment/env_helpers.py
  src/super_gradients/sanity_check/env_sanity_check.py
  src/super_gradients/training/utils/distributed_training_utils.py
Labels: size/M

#478 fix vulnerability by Snyk
  requirements.txt
Labels: size/XS

#480 Apply black formatting on files affected by PP-Yolo-E PR
  src/super_gradients/common/object_names.py
  src/super_gradients/training/losses/__init__.py
  src/super_gradients/training/losses/all_losses.py
  src/super_gradients/training/metrics/detection_metrics.py
  src/super_gradients/training/models/detection_models/yolo_base.py
  src/super_gradients/training/utils/callbacks/callbacks.py
  src/super_gradients/training/utils/ssd_utils.py
Labels: size/XL

#483 Apply black on callback
  src/super_gradients/training/utils/callbacks/__init__.py
  tests/integration_tests/deci_lab_export_test.py
Labels: size/L

#485 Apply black on sg_training_utils
  src/super_gradients/training/utils/sg_trainer_utils.py
Labels: size/L

#486 intuitive error on model get
  src/super_gradients/common/plugins/deci_client.py
  src/super_gradients/common/sg_loggers/deci_platform_sg_logger.py
  src/super_gradients/training/models/model_factory.py
  src/super_gradients/training/utils/callbacks/callbacks.py
Labels: size/L

#472 fix os.putenv('WANDB_BASE_URL') to os.environ["WANDB_BASE_URL"]
  src/super_gradients/common/sg_loggers/wandb_sg_logger.py
Labels: size/M

#488 fix: Support hydra lists
  src/super_gradients/training/utils/module_utils.py
Labels: size/XS

#487 refactor: Format pretrained_models_test
  tests/integration_tests/pretrained_models_test.py
Labels: size/XXL

#490 Hotfix/alg 278 det circular imports
  src/super_gradients/common/factories/__init__.py
  src/super_gradients/modules/detection_modules.py
  src/super_gradients/training/models/detection_models/customizable_detector.py
Labels: size/L

#489 Feature/alg 287 fix mobilenet
  src/super_gradients/training/models/classification_models/mobilenet.py
  src/super_gradients/training/models/classification_models/mobilenetv2.py
Labels: size/M

#481 Feature/alg 287 refactor ssd
  src/super_gradients/modules/detection_modules.py
  src/super_gradients/recipes/arch_params/ssd_lite_mobilenetv2_arch_params.yaml
  src/super_gradients/recipes/arch_params/ssd_mobilenetv1_arch_params.yaml
  src/super_gradients/training/models/detection_models/ssd.py
  src/super_gradients/training/utils/hydra_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/XL

#491 Use Gloo backend when running on Windows
  src/super_gradients/training/sg_trainer/sg_trainer.py
Labels: size/XS

#462 fix documentation scripts
  documentation/assets/SG_img/Classification 1500x900.png
  documentation/assets/SG_img/Classification.png
  documentation/assets/SG_img/Classification@2x.png
  documentation/assets/SG_img/Classification@2xDark.png
  documentation/assets/SG_img/Object Detection.png
  documentation/assets/SG_img/Object Detection@2x.png
  documentation/assets/SG_img/Object Detection@2xDark.png
  documentation/assets/SG_img/Object detection 1500X900.png
  documentation/assets/SG_img/SG - Horizontal Glow 2.png
  documentation/assets/SG_img/SG - Horizontal Glow.png
  documentation/assets/SG_img/SG_sticker.png
  documentation/assets/SG_img/Segmentation 1500x900 .png
  documentation/assets/SG_img/Semantic Segmentation.png
  documentation/assets/SG_img/Semantic Segmentation@2x.png
  documentation/assets/SG_img/Semantic Segmentation@2xDark.png
  documentation/assets/SG_img/detection-demo.png
  documentation/source/_static/custom.css
  documentation/source/conf.py
  documentation/source/generated/super_gradients.common.abstractions.rst
  documentation/source/generated/super_gradients.common.auto_logging.rst
  documentation/source/generated/super_gradients.common.aws_connection.rst
  documentation/source/generated/super_gradients.common.data_connection.rst
  documentation/source/generated/super_gradients.common.data_interface.rst
  documentation/source/generated/super_gradients.common.data_types.rst
  documentation/source/generated/super_gradients.common.decorators.rst
  documentation/source/generated/super_gradients.common.environment.rst
  documentation/source/index.rst
  documentation/source/sphinx-requirements.txt
  documentation/source/super_gradients.common.abstractions.rst
  documentation/source/super_gradients.common.auto_logging.rst
  documentation/source/super_gradients.common.aws_connection.rst
  documentation/source/super_gradients.common.data_connection.rst
  documentation/source/super_gradients.common.data_interface.rst
  documentation/source/super_gradients.common.data_types.enum.rst
  documentation/source/super_gradients.common.data_types.rst
  documentation/source/super_gradients.common.decorators.rst
  documentation/source/super_gradients.common.environment.rst
  documentation/source/super_gradients.common.rst
  documentation/source/super_gradients.training.datasets.classification_datasets.rst
  documentation/source/super_gradients.training.datasets.dataset_interfaces.rst
  documentation/source/super_gradients.training.datasets.detection_datasets.rst
  documentation/source/super_gradients.training.datasets.rst
  documentation/source/super_gradients.training.datasets.segmentation_datasets.rst
  documentation/source/super_gradients.training.exceptions.rst
  documentation/source/super_gradients.training.legacy.rst
  documentation/source/super_gradients.training.losses.rst
  documentation/source/super_gradients.training.metrics.rst
  documentation/source/super_gradients.training.models.rst
  documentation/source/super_gradients.training.rst
  documentation/source/super_gradients.training.sg_model.rst
  documentation/source/super_gradients.training.utils.optimizers.rst
  documentation/source/super_gradients.training.utils.rst
  scripts/generate_docs.sh
  src/super_gradients/common/__init__.py
  src/super_gradients/common/data_types/enum/strict_load.py
Labels: size/XXL

#304 Feature/sg 000 qat
  .circleci/config.yml
  requirements.txt
  setup.py
  src/super_gradients/examples/quantization/__init__.py
  src/super_gradients/examples/quantization/non_default_calibrators_example.py
  src/super_gradients/examples/quantization/ptq_e2e_example.py
  src/super_gradients/examples/quantization/register_quantization_mapping_with_decorator_example.py
  src/super_gradients/examples/quantization/resnet_qat_example.py
  src/super_gradients/examples/quantization/skipping_quantization_example.py
  src/super_gradients/examples/quantization/vanilla_quantize_all_example.py
  src/super_gradients/examples/resnet_qat/resnet_qat_example.py
  src/super_gradients/modules/quantization/__init__.py
  src/super_gradients/modules/quantization/resnet_bottleneck.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
  src/super_gradients/training/utils/quantization/__init__.py
  src/super_gradients/training/utils/quantization/calibrator.py
  src/super_gradients/training/utils/quantization/core.py
  src/super_gradients/training/utils/quantization/export.py
  src/super_gradients/training/utils/quantization/selective_quantization_utils.py
  src/super_gradients/training/utils/quantization_utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/integration_tests/qat_integration_test.py
  tests/unit_tests/quantization_utility_tests.py
Labels: size/XXL

#437 Feature/SG-195 Detection output adapter
  src/super_gradients/training/utils/bbox_formats/__init__.py
  src/super_gradients/training/utils/bbox_formats/bbox_format.py
  src/super_gradients/training/utils/bbox_formats/cxcywh.py
  src/super_gradients/training/utils/bbox_formats/normalized_cxcywh.py
  src/super_gradients/training/utils/bbox_formats/normalized_xywh.py
  src/super_gradients/training/utils/bbox_formats/normalized_xyxy.py
  src/super_gradients/training/utils/bbox_formats/xywh.py
  src/super_gradients/training/utils/bbox_formats/xyxy.py
  src/super_gradients/training/utils/bbox_formats/yxyx.py
  src/super_gradients/training/utils/output_adapters/__init__.py
  src/super_gradients/training/utils/output_adapters/detection_adapter.py
  src/super_gradients/training/utils/output_adapters/formats.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/bbox_formats_test.py
  tests/unit_tests/detection_output_adapter_test.py
Labels: size/L

#454 Feature/sg 387 upload console logs for pro users
  .circleci/config.yml
  src/super_gradients/__init__.py
  src/super_gradients/common/plugins/exception_monitoring.py
  src/super_gradients/training/utils/sg_trainer_utils.py
Labels: size/XL

#493 Crash tip
  src/super_gradients/__init__.py
  src/super_gradients/common/__init__.py
  src/super_gradients/common/crash_handler/__init__.py
  src/super_gradients/common/crash_handler/crash_handler.py
  src/super_gradients/common/crash_handler/crash_tips.py
  src/super_gradients/common/crash_handler/crash_tips_setup.py
  src/super_gradients/common/crash_handler/exception.py
  src/super_gradients/common/crash_handler/exception_monitoring_setup.py
  src/super_gradients/common/crash_handler/utils.py
  src/super_gradients/common/plugins/exception_monitoring.py
  tests/unit_tests/crash_tips_test.py
Labels: include in feature update
