Repository Deci-AI/super-gradients, pull requests merged in 2022-04, with the labels that each got.

#158 Feature/sg 70 kd loss
  .circleci/config.yml
  src/super_gradients/training/kd_model/kd_model.py
  src/super_gradients/training/losses/kd_losses.py
  src/super_gradients/training/models/classification_models/mobilenetv2.py
  src/super_gradients/training/models/classification_models/mobilenetv3.py
  src/super_gradients/training/models/kd_modules/kd_module.py
  src/super_gradients/training/params.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/callbacks.py
  src/super_gradients/training/utils/sg_model_utils.py
  tests/unit_tests/kd_model_test.py
Labels: size/L

#163 Feature/sg 57 vanilla vi t
  requirements.txt
  src/super_gradients/recipes/arch_params/vit_base_arch_params.yaml
  src/super_gradients/recipes/checkpoint_params/vit_base_imagenet_checkpoint_params.yaml
  src/super_gradients/recipes/imagenet_vit_base.yaml
  src/super_gradients/recipes/imagenet_vit_large.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_vit_train_params.yaml
  src/super_gradients/training/models/__init__.py
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/classification_models/vit.py
  src/super_gradients/training/pretrained_models.py
  src/super_gradients/training/sg_model/sg_model.py
  tests/deci_core_unit_test_suite_runner.py
  tests/integration_tests/pretrained_models_test.py
  tests/unit_tests/vit_unit_test.py
Labels: size/L

#166 Hotfix/sg 000 clip grad norm bug
  src/super_gradients/recipes/training_hyperparams/default_train_params.yaml
Labels: size/XS

#171 Readme/sg update
  README.md
  docs/user_guide.html
  documentation/source/user_guide.md
Labels: size/XXL

#172 user guide html updates
  docs/CONTRIBUTING.html
  docs/LICENSE.html
  docs/genindex.html
  docs/index.html
  docs/objects.inv
  docs/py-modindex.html
  docs/search.html
  docs/searchindex.js
  docs/super_gradients.common.abstractions.html
  docs/super_gradients.common.auto_logging.html
  docs/super_gradients.common.aws_connection.html
  docs/super_gradients.common.data_connection.html
  docs/super_gradients.common.data_interface.html
  docs/super_gradients.common.data_types.enum.html
  docs/super_gradients.common.data_types.html
  docs/super_gradients.common.decorators.html
  docs/super_gradients.common.environment.html
  docs/super_gradients.common.html
  docs/super_gradients.html
  docs/super_gradients.training.datasets.classification_datasets.html
  docs/super_gradients.training.datasets.dataset_interfaces.html
  docs/super_gradients.training.datasets.detection_datasets.html
  docs/super_gradients.training.datasets.html
  docs/super_gradients.training.datasets.segmentation_datasets.html
  docs/super_gradients.training.exceptions.html
  docs/super_gradients.training.html
  docs/super_gradients.training.legacy.html
  docs/super_gradients.training.losses.html
  docs/super_gradients.training.metrics.html
  docs/super_gradients.training.models.html
  docs/super_gradients.training.sg_model.html
  docs/super_gradients.training.utils.html
  docs/super_gradients.training.utils.optimizers.html
Labels: size/XL

#176 torchmetrics version fix in master
  requirements.txt
Labels: size/XS

#170 added dependency review
  .github/workflows/dependency_review.yaml
Labels: size/S

#178 Feature/sg 92 remove tf requirement
  requirements.txt
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/__init__.py
Labels: size/XS

#177 Bugfix/sg 99 stdc single class bug
  src/super_gradients/training/exceptions/loss_exceptions.py
  src/super_gradients/training/losses/ohem_ce_loss.py
  src/super_gradients/training/losses/stdc_loss.py
  src/super_gradients/training/metrics/segmentation_metrics.py
  src/super_gradients/training/utils/callbacks.py
Labels: size/L

#181 feature/SG-106_lamb_optimizer
  src/super_gradients/common/factories/optimizers_type_factory.py
  src/super_gradients/training/utils/optimizers/lamb.py
Labels: size/L

#186 Feature/sg 118 kd model additional logging
  src/super_gradients/training/kd_model/kd_model.py
  src/super_gradients/training/sg_model/sg_model.py
Labels: size/M

#188 docs: Comment all the stages of the loss
  src/super_gradients/training/losses/yolox_loss.py
Labels: size/M

#183 Feature/sg 111 kd teacher input adaptor
  src/super_gradients/training/models/kd_modules/kd_module.py
  src/super_gradients/training/utils/module_utils.py
  tests/unit_tests/kd_model_test.py
Labels: size/M

#190 Feature/sg 36 yolox cfgs
  src/super_gradients/recipes/coco2017_yolox.yaml
Labels: size/XS
