Repository Deci-AI/super-gradients, pull requests merged in 2022-08, with the labels that each got.

#284 Fix training prints
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/sg_model_utils.py
Labels: size/M

#274 Remove all elasticsearch references
  requirements.txt
  src/super_gradients/common/abstractions/abstract_logger.py
  src/super_gradients/common/auto_logging/auto_logger.py
  src/super_gradients/common/environment/environment_config.py
Labels: size/L

#286 Sg/yolox readme
  README.md
Labels: size/M

#289 Fix flake8 errors in super_gradients/training
  src/super_gradients/training/__init__.py
  src/super_gradients/training/datasets/data_augmentation.py
  src/super_gradients/training/datasets/dataset_interfaces/__init__.py
  src/super_gradients/training/datasets/datasets_utils.py
  src/super_gradients/training/datasets/detection_datasets/__init__.py
  src/super_gradients/training/datasets/segmentation_datasets/__init__.py
  src/super_gradients/training/exceptions/kd_model_exceptions.py
  src/super_gradients/training/kd_model/kd_model.py
  src/super_gradients/training/losses/ssd_loss.py
  src/super_gradients/training/losses/stdc_loss.py
  src/super_gradients/training/losses/yolox_loss.py
  src/super_gradients/training/metrics/__init__.py
  src/super_gradients/training/models/classification_models/mobilenetv3.py
  src/super_gradients/training/models/detection_models/yolo_base.py
  src/super_gradients/training/models/segmentation_models/laddernet.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/trainer.py
  src/super_gradients/training/transforms/transforms.py
  src/super_gradients/training/utils/callbacks.py
  src/super_gradients/training/utils/checkpoint_utils.py
  src/super_gradients/training/utils/detection_utils.py
  src/super_gradients/training/utils/export_utils.py
  src/super_gradients/training/utils/get_model_stats.py
  src/super_gradients/training/utils/quantization_utils.py
  src/super_gradients/training/utils/ssd_utils.py
Labels: size/L

#290 Fix flake8 errors in test
  tests/integration_tests/conversion_callback_test.py
  tests/integration_tests/pretrained_models_test.py
  tests/unit_tests/dataset_statistics_test.py
  tests/unit_tests/export_utils_test.py
  tests/unit_tests/lr_warmup_test.py
  tests/unit_tests/mask_loss_test.py
  tests/unit_tests/phase_context_test.py
  tests/unit_tests/test_all_datasets_imports.py
  tests/unit_tests/test_without_train_test.py
  tests/unit_tests/train_with_intialized_param_args_test.py
Labels: size/L

#291 Fix flake8 errors in different folders
  src/super_gradients/common/auto_logging/__init__.py
  src/super_gradients/common/aws_connection/__init__.py
  src/super_gradients/common/aws_connection/aws_connector.py
  src/super_gradients/common/aws_connection/aws_secrets_manager_connector.py
  src/super_gradients/common/data_connection/__init__.py
  src/super_gradients/common/decorators/__init__.py
  src/super_gradients/common/environment/environment_config.py
  src/super_gradients/common/factories/datasets_factory.py
  src/super_gradients/common/factories/transforms_factory.py
  src/super_gradients/common/sg_loggers/deci_platform_sg_logger.py
  src/super_gradients/common/sg_loggers/wandb_sg_logger.py
  src/super_gradients/examples/deci_lab_export_example/deci_lab_export_example.py
  src/super_gradients/sanity_check/__init__.py
  src/super_gradients/sanity_check/env_sanity_check.py
Labels: size/M

#288 Add linter (flake8) check in CI
  .circleci/config.yml
  scripts/flake8-config
Labels: size/S

#292 Feature/sg 172 reproduce ssd with new coco dataset interface
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_ssd_lite_mobilenet_v2_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_yolox_dataset_params.yaml
  src/super_gradients/recipes/training_hyperparams/coco2017_ssd_lite_mobilenet_v2_train_params.yaml
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/pretrained_models.py
  src/super_gradients/training/utils/ssd_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#293 Update README.md
  README.md
Labels: size/S

#294 affine args for filtering fixed
  src/super_gradients/training/transforms/transforms.py
Labels: size/M

#282 Add notebook for SG-Lab connection
  src/super_gradients/examples/SG_quickstart_tensorboard_logger.ipynb
Labels: size/XL

#296 Update README.md
  README.md
Labels: size/XS

#295 Feature/sg 190 take out old coco related objects
  src/super_gradients/common/factories/datasets_factory.py
  src/super_gradients/examples/legacy/ssd_coco.py
  src/super_gradients/recipes/coco2017_ssd_mobilenet_v1.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_dataset_params.yaml
  src/super_gradients/training/__init__.py
  src/super_gradients/training/datasets/__init__.py
  src/super_gradients/training/datasets/all_datasets.py
  src/super_gradients/training/datasets/dataset_interfaces/__init__.py
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/datasets_utils.py
  src/super_gradients/training/datasets/detection_datasets/__init__.py
  src/super_gradients/training/datasets/detection_datasets/coco_detection.py
  src/super_gradients/training/datasets/detection_datasets/coco_detection_yolox.py
  src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
  src/super_gradients/training/datasets/detection_datasets/pascal_voc_detection.py
  src/super_gradients/training/transforms/transforms.py
  src/super_gradients/training/utils/detection_utils.py
  tests/integration_tests/detection_subclass_test.py
  tests/integration_tests/pretrained_models_test.py
  tests/unit_tests/dataset_statistics_test.py
  tests/unit_tests/detection_utils_test.py
Labels: size/XXL

#297 coco dataset old refs renamed
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/coco2017_yolox.yaml
Labels: size/XS

#302 Add images via upload for Ultralytics readme
  documentation/assets/SG_img/Deci_img/Deci_add_model.png
  documentation/assets/SG_img/Deci_img/Deci_deploy_button.png
  documentation/assets/SG_img/Deci_img/Deci_deploy_model.png
  documentation/assets/SG_img/Deci_img/Deci_insights.png
  documentation/assets/SG_img/Deci_img/Deci_lab.png
  documentation/assets/SG_img/Deci_img/Deci_runtime_optimization.png
  documentation/assets/SG_img/Deci_img/Deci_signup.png
Labels: size/XS

#300 Feature/sg 000 yolo leftovers
  src/super_gradients/recipes/training_hyperparams/coco2017_yolox_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/default_train_params.yaml
  src/super_gradients/training/models/detection_models/csp_darknet53.py
  src/super_gradients/training/models/detection_models/darknet53.py
  src/super_gradients/training/models/detection_models/yolo_base.py
  src/super_gradients/training/utils/callbacks.py
  src/super_gradients/training/utils/detection_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#299 DDRNet train recipe
  src/super_gradients/examples/ddrnet_cityscapes/ddrnet_segmetation_example.py
  src/super_gradients/examples/ddrnet_imagenet/__init__.py
  src/super_gradients/examples/ddrnet_imagenet/ddrnet_classification_example.py
  src/super_gradients/recipes/cityscapes_ddrnet.yaml
  src/super_gradients/recipes/cityscapes_stdc_base.yaml
  src/super_gradients/recipes/training_hyperparams/cityscapes_default_train_params.yaml
  src/super_gradients/training/models/segmentation_models/ddrnet.py
  src/super_gradients/training/pretrained_models.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#303 Sg/ddr net new recipes+checkpoints
  README.md
Labels: size/XS

#278 Adding new version of detection dataset, PascalVOC and PascalVOC dataset interface
  src/super_gradients/training/datasets/__init__.py
  src/super_gradients/training/datasets/dataset_interfaces/__init__.py
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/datasets_conf.py
  src/super_gradients/training/datasets/detection_datasets/__init__.py
  src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
  src/super_gradients/training/datasets/detection_datasets/pascal_voc_detection.py
  src/super_gradients/training/exceptions/dataset_exceptions.py
  src/super_gradients/training/utils/detection_utils.py
  src/super_gradients/training/utils/utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/integration_tests/detection_dataset_test.py
  tests/unit_tests/dataset_interface_test.py
  tests/unit_tests/detection_sub_classing_test.py
  tests/unit_tests/detection_sub_sampling_test.py
Labels: size/XXL

#305 Update README.md
  README.md
Labels: size/XS

#306 move enums out of SgModel
  src/super_gradients/common/__init__.py
  src/super_gradients/common/data_types/__init__.py
  src/super_gradients/common/data_types/enum/__init__.py
  src/super_gradients/common/data_types/enum/evaluation_type.py
  src/super_gradients/common/data_types/enum/multi_gpu_mode.py
  src/super_gradients/common/data_types/enum/strict_load.py
  src/super_gradients/training/sg_model/sg_model.py
Labels: size/L

#309 Fix scale between rescaling batches
  src/super_gradients/training/datasets/datasets_utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/multi_scaling_test.py
Labels: size/M

#308 Hotfix detection cache: Add hash in name when caching
  src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/detection_caching.py
Labels: size/L

#307 Hotfix/sg 000 fix image loading new detectiondataset
  src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
  src/super_gradients/training/datasets/detection_datasets/pascal_voc_detection.py
  src/super_gradients/training/utils/utils.py
  tests/unit_tests/detection_caching.py
  tests/unit_tests/detection_sub_classing_test.py
  tests/unit_tests/detection_sub_sampling_test.py
Labels: size/M

#317 Update README.md
  README.md
Labels: size/XS

#298 Feature/sg 171 make coco inherit from detection dataset
  src/super_gradients/recipes/dataset_params/coco_detection_ssd_lite_mobilenet_v2_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_yolox_dataset_params.yaml
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/detection_datasets/coco_detection.py
  src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
  src/super_gradients/training/datasets/detection_datasets/pascal_voc_detection.py
  tests/integration_tests/detection_dataset_test.py
  tests/unit_tests/dataset_interface_test.py
  tests/unit_tests/detection_caching.py
  utils_script/create_sub_coco.py
Labels: size/XL

#318 Feature/sg 219 remove coco hard coded params
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_ssd_lite_mobilenet_v2_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_yolox_dataset_params.yaml
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#314 added two assertions for num classes must be bigger than 1
  src/super_gradients/training/metrics/segmentation_metrics.py
Labels: size/XS

#322 Fix coco recipes
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_ssd_lite_mobilenet_v2_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_yolox_dataset_params.yaml
Labels: size/S

#324 feature/hydra outputs dir synced with checkpoints
  src/super_gradients/common/environment/env_helpers.py
  src/super_gradients/common/environment/environment_config.py
Labels: size/S

#327 Fix: add setNumThreads to datasets and transforms
  src/super_gradients/training/datasets/__init__.py
  src/super_gradients/training/transforms/__init__.py
Labels: size/XS

#330 remove redundant _target_ tags
  src/super_gradients/recipes/cityscapes_ddrnet.yaml
  src/super_gradients/recipes/cityscapes_stdc_base.yaml
  src/super_gradients/recipes/coco_segmentation_shelfnet_lw.yaml
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/imagenet_mobilenetv2.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3.yaml
  src/super_gradients/recipes/imagenet_regnetY.yaml
  src/super_gradients/recipes/imagenet_repvgg.yaml
  src/super_gradients/recipes/imagenet_resnet50.yaml
  src/super_gradients/recipes/imagenet_resnet50_kd.yaml
  src/super_gradients/recipes/training_hyperparams/coco_segmentation_shelfnet_lw_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_efficientnet_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_mobilenetv2_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_mobilenetv3_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_regnetY_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_repvgg_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_resnet50_kd_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_resnet50_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_vit_train_params.yaml
Labels: size/L

#326 Feature/SG-245 Support for register model in model's factory
  src/super_gradients/training/models/__init__.py
  src/super_gradients/training/models/model_registry.py
  src/super_gradients/training/models/user_models/README.md
  src/super_gradients/training/models/user_models/__init__.py
  tests/unit_tests/model_registry_test.py
Labels: size/L

#328 Feature/sg 217 refactor dataset interface
  src/super_gradients/common/factories/samplers_factory.py
  src/super_gradients/common/factories/transforms_factory.py
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_ssd_lite_mobilenet_v2_dataset_params.yaml
  src/super_gradients/training/dataloaders/__init__.py
  src/super_gradients/training/dataloaders/dataloader_factory.py
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
  src/super_gradients/training/datasets/samplers/infinite_sampler.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
  tests/unit_tests/datalaoder_factory_test.py
  tests/unit_tests/initialize_with_dataloaders_test.py
Labels: size/L

#320 Feature/sg 143 document commands for all recipes
  README.md
  src/super_gradients/recipes/checkpoint_params/default_checkpoint_params.yaml
  src/super_gradients/recipes/cifar10_resnet.yaml
  src/super_gradients/recipes/cityscapes_ddrnet.yaml
  src/super_gradients/recipes/cityscapes_regseg48.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg75.yaml
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/recipes/coco_segmentation_shelfnet_lw.yaml
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/imagenet_mobilenetv2.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_base.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_large.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_small.yaml
  src/super_gradients/recipes/imagenet_regnetY.yaml
  src/super_gradients/recipes/imagenet_repvgg.yaml
  src/super_gradients/recipes/imagenet_resnet50.yaml
  src/super_gradients/recipes/imagenet_resnet50_kd.yaml
  src/super_gradients/recipes/imagenet_vit_base.yaml
  src/super_gradients/recipes/imagenet_vit_large.yaml
  src/super_gradients/recipes/training_hyperparams/cifar10_resnet_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/default_train_params.yaml
  src/super_gradients/training/utils/utils.py
Labels: size/L

#336 fix: Prevent loosing weight_decay from params
  src/super_gradients/training/utils/optimizer_utils.py
Labels: size/XS

#337 Feature/sg 216 refactor test datasets
  src/super_gradients/training/dataloaders/dataloader_factory.py
  tests/unit_tests/datalaoder_factory_test.py
Labels: size/M

#331 Feature/sg 216 refactor imagenet dataloader
  src/super_gradients/common/factories/transforms_factory.py
  src/super_gradients/recipes/checkpoint_params/default_checkpoint_params.yaml
  src/super_gradients/recipes/dataset_params/imagenet_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/imagenet_efficientnet_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/imagenet_mobilenetv2_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/imagenet_mobilenetv3_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/imagenet_regnetY_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/imagenet_resnet50_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/imagenet_resnet50_kd_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/imagenet_vit_base_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/tiny_imagenet_dataset_params.yaml
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/imagenet_mobilenetv2.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_base.yaml
  src/super_gradients/recipes/imagenet_regnetY.yaml
  src/super_gradients/recipes/imagenet_resnet50.yaml
  src/super_gradients/recipes/imagenet_resnet50_kd.yaml
  src/super_gradients/recipes/imagenet_vit_base.yaml
  src/super_gradients/recipes/imagenet_vit_large.yaml
  src/super_gradients/training/dataloaders/dataloader_factory.py
  src/super_gradients/training/datasets/__init__.py
  src/super_gradients/training/datasets/auto_augment.py
  src/super_gradients/training/datasets/classification_datasets/__init__.py
  src/super_gradients/training/datasets/classification_datasets/imagenet_dataset.py
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/datasets_utils.py
  tests/unit_tests/datalaoder_factory_test.py
Labels: size/XL

#340 teacher adpator freeze + map location cpu for all pretrained models
  src/super_gradients/recipes/imagenet_resnet50_kd.yaml
  src/super_gradients/training/models/kd_modules/kd_module.py
  src/super_gradients/training/utils/checkpoint_utils.py
Labels: size/S
