Repository Deci-AI/super-gradients, pull requests merged in 2022-05, with the labels that each got.

#174 Add Dice and BinaryDice metrics
  src/super_gradients/common/factories/metrics_factory.py
  src/super_gradients/training/metrics/segmentation_metrics.py
Labels: size/L

#193 Feature/ops 1190 orb
  .circleci/config.yml
Labels: size/XL

#184 Feature/sg 107 repeated agumentation sampler
  src/super_gradients/recipes/dataset_params/imagenet_dataset_params.yaml
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/samplers/__init__.py
  src/super_gradients/training/datasets/samplers/repeated_augmentation_sampler.py
Labels: size/L

#196 fix: Build a correct YOLOX-nano with depthwise separable convs
  src/super_gradients/recipes/arch_params/yolo_arch_params.yaml
  src/super_gradients/recipes/arch_params/yolox_nano_arch_params.yaml
  src/super_gradients/training/models/detection_models/csp_darknet53.py
  src/super_gradients/training/models/detection_models/yolov5_base.py
  src/super_gradients/training/models/detection_models/yolox.py
Labels: size/M

#198 torchmetrics version updated and unit test fixed
  requirements.txt
  tests/unit_tests/train_with_intialized_param_args_test.py
Labels: size/S

#203 requirements deps modified
  requirements.txt
Labels: size/XS

#151 Adding a notebook with upload to the Deci Lab
  README.md
  requirements.txt
  src/super_gradients/examples/SG_quickstart_model_upload_deci_lab.ipynb
  src/super_gradients/examples/deci_lab_export_example/deci_lab_export_example.py
  src/super_gradients/training/utils/callbacks.py
  tests/integration_tests/conversion_callback_test.py
Labels: size/XXL

#162 upload example with auth token and no credentials
  README.md
  requirements.txt
  src/super_gradients/examples/deci_lab_export_example/deci_lab_export_example.py
  src/super_gradients/training/utils/callbacks.py
Labels: size/S
