Repository Deci-AI/super-gradients, pull requests merged in 2022-01, with the labels that each got.

#66 Hotfix/alg 235 override skip connections
  src/super_gradients/recipes/arch_params/yolo_arch_params.yaml
  src/super_gradients/training/models/detection_models/yolov5.py
Labels: size/XS

#90 Update README.md
  README.md
Labels: size/S

#87 line removed
  tests/integration_tests/deci_lab_export_test.py
Labels: size/XS

#61 fix the writing of hyperparams in log, tensorboard and wandb
  src/super_gradients/common/sg_loggers/base_sg_logger.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/detection_utils.py
Labels: size/S

#54 Feature/dle 929 auto multi gpu
  src/super_gradients/recipes/cifar10_resnet.yaml
  src/super_gradients/recipes/coco2017_yolov5.yaml
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3.yaml
  src/super_gradients/recipes/imagenet_regnetY800.yaml
  src/super_gradients/recipes/imagenet_repvgg.yaml
  src/super_gradients/recipes/imagenet_resnet50.yaml
  src/super_gradients/training/sg_model/sg_model.py
Labels: size/M

#65 added a new callback phase and calling it on best metric
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/callbacks.py
Labels: size/S

#71 added an option to upload any file from the checkpoint dir
  src/super_gradients/common/sg_loggers/abstract_sg_logger.py
  src/super_gradients/common/sg_loggers/base_sg_logger.py
  src/super_gradients/common/sg_loggers/wandb_sg_logger.py
Labels: size/S

#93 POST_TRAINING callbacks before closing sg_logger
  src/super_gradients/training/sg_model/sg_model.py
Labels: size/XS

#62 remove max_epochs limitation
  src/super_gradients/training/params.py
Labels: size/XS

#95 Feature/dle 1012 pypi installation
  .circleci/config.yml
  setup.py
Labels: size/M

#97 Update README.md
  README.md
Labels: size/S

#70 Feature/alg 257 save code wandb
  src/super_gradients/common/sg_loggers/wandb_sg_logger.py
Labels: size/M

#98 Update setup.py
  setup.py
Labels: size/XS

#100 Bugfix/dle 1036 checkpoint module bug
  src/super_gradients/common/sg_loggers/base_sg_logger.py
  src/super_gradients/training/sg_model/sg_model.py
  tests/unit_tests/strictload_enum_test.py
Labels: size/S

#96 Bugfix/dle 1004 regnet recipes update
  src/super_gradients/recipes/imagenet_regnetY.yaml
  src/super_gradients/recipes/training_hyperparams/default_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/imagenet_regnetY_train_params.yaml
  src/super_gradients/training/params.py
  src/super_gradients/training/utils/callbacks.py
Labels: size/M

#101 Bugfix/dle 1004 regnet recipes update
  src/super_gradients/recipes/imagenet_regnetY.yaml
Labels: size/S

#92 Feature/dle 742 replace head detection models
  docs/_modules/super_gradients/training/datasets/dataset_interfaces/dataset_interface.html
  docs/_modules/super_gradients/training/datasets/detection_datasets/pascal_voc_detection.html
  src/super_gradients/examples/yolov5_transfer_learning_example/__init__.py
  src/super_gradients/examples/yolov5_transfer_learning_example/yolov5_transfer_learning_example.py
  src/super_gradients/recipes/dataset_params/coco_detection_dataset_params.yaml
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/detection_datasets/__init__.py
  src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
  src/super_gradients/training/datasets/detection_datasets/pascal_voc_detection.py
  src/super_gradients/training/losses/yolo_v5_loss.py
  src/super_gradients/training/models/detection_models/yolov5.py
  src/super_gradients/training/utils/checkpoint_utils.py
Labels: size/L

#94 Add STDC segmentation model
  src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg75.yaml
  src/super_gradients/recipes/dataset_params/cityscapes_dataset_params.yaml
  src/super_gradients/recipes/training_hyperparams/cityscapes_stdc_train_params.yaml
  src/super_gradients/training/datasets/segmentation_datasets/segmentation_dataset.py
  src/super_gradients/training/losses/dice_loss.py
  src/super_gradients/training/losses/loss_utils.py
  src/super_gradients/training/losses/ohem_ce_loss.py
  src/super_gradients/training/losses/stdc_loss.py
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/segmentation_models/stdc.py
  src/super_gradients/training/pretrained_models.py
  src/super_gradients/training/utils/segmentation_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/XXL

#106 Update STDC family in README.md
  README.md
Labels: size/S

#107 Update README.md badges
  README.md
Labels: size/XS

#108 docs: Remove an obsolete comment
  src/super_gradients/training/utils/utils.py
Labels: size/XS

#109 Update README.md
  README.md
Labels: size/S

#111 Fixed missing checkpoints_dir_path piping to base logger
  src/super_gradients/common/sg_loggers/wandb_sg_logger.py
Labels: size/XS

#99 Print the full location of checkpoints when saved in training
  src/super_gradients/common/sg_loggers/base_sg_logger.py
Labels: size/XS

#112 Fixed redundant parameter in SegmentationTransform.__repr__
  src/super_gradients/training/utils/segmentation_utils.py
Labels: size/XS

#104 fix: Allow to override augs in CoCoSegmentation
  src/super_gradients/training/datasets/segmentation_datasets/coco_segmentation.py
Labels: size/S

#105 Added factories
  src/super_gradients/common/decorators/factory_decorator.py
  src/super_gradients/common/factories/__init__.py
  src/super_gradients/common/factories/base_factory.py
  src/super_gradients/common/factories/callbacks_factory.py
  src/super_gradients/common/factories/datasets_factory.py
  src/super_gradients/common/factories/list_factory.py
  src/super_gradients/common/factories/losses_factory.py
  src/super_gradients/common/factories/metrics_factory.py
  src/super_gradients/common/factories/optimizers_type_factory.py
  src/super_gradients/recipes/cifar10_resnet.yaml
  src/super_gradients/recipes/test_resnet.yaml
  src/super_gradients/recipes/training_hyperparams/cifar10_resnet_train_params.yaml
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/optimizer_utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/__init__.py
  tests/unit_tests/factories_test.py
Labels: size/L

#113 Update README.md
  README.md
Labels: size/S

#110 Bug/dle 1013 fixes for transfer learning
  src/super_gradients/examples/TransferLearningDetection.ipynb
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/detection_datasets/pascal_voc_detection.py
  src/super_gradients/training/utils/utils.py
Labels: size/XXL

#115 updated notebook
  src/super_gradients/examples/TransferLearningDetection.ipynb
Labels: size/XXL

#116 Update README.md
  README.md
Labels: size/S

#117 Feature/dle 1081 add detection viz callback
  src/super_gradients/examples/yolov5_transfer_learning_example/yolov5_transfer_learning_example.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/callbacks.py
Labels: size/M

#120 - added a new factory for transforms
  src/super_gradients/common/decorators/factory_decorator.py
  src/super_gradients/common/factories/transforms_factory.py
  src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
  src/super_gradients/recipes/training_hyperparams/cityscapes_stdc_train_params.yaml
  src/super_gradients/training/datasets/segmentation_datasets/segmentation_dataset.py
  src/super_gradients/training/losses/all_losses.py
  src/super_gradients/training/sg_model/sg_model.py
Labels: size/L

#122 fix pad short to crop size
  src/super_gradients/training/utils/segmentation_utils.py
Labels: size/XS
