Repository Deci-AI/super-gradients, pull requests merged in 2022-07, with the labels that each got.

#224 Feature/sg 13 forward pass prep fn
  src/super_gradients/training/datasets/datasets_utils.py
  src/super_gradients/training/params.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/distributed_training_utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/forward_pass_prep_fn_test.py
Labels: size/L

#233 Feature/alg 511 reproduce ssd
  src/super_gradients/recipes/coco_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/losses/ssd_loss.py
  src/super_gradients/training/models/detection_models/ssd.py
  src/super_gradients/training/pretrained_models.py
  src/super_gradients/training/utils/detection_utils.py
  src/super_gradients/training/utils/ssd_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/XL

#237 fix: Support any model width multiplier
  src/super_gradients/recipes/arch_params/yolo_arch_params.yaml
  src/super_gradients/training/models/detection_models/yolov5_base.py
  tests/unit_tests/yolov5_unit_test.py
Labels: size/M

#240 fixed
  src/super_gradients/training/sg_model/sg_model.py
Labels: size/XS

#241 unit test added
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/update_param_groups_unit_test.py
Labels: size/M

#238 Fix failing yolo param groups test
  tests/unit_tests/yolov5_unit_test.py
Labels: size/XS

#242 refactor: Separate function for regnet slope to blocks
  src/super_gradients/training/models/classification_models/regnet.py
Labels: size/M

#244 fix: Update connectors name in mobilenetv2
  src/super_gradients/training/models/classification_models/mobilenetv2.py
Labels: size/XS

#232 Feature/sg 156 qat support
  requirements.txt
  src/super_gradients/common/sg_loggers/base_sg_logger.py
  src/super_gradients/examples/resnet_qat/__init__.py
  src/super_gradients/examples/resnet_qat/resnet_qat_example.py
  src/super_gradients/recipes/training_hyperparams/default_train_params.yaml
  src/super_gradients/training/params.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/callbacks.py
  src/super_gradients/training/utils/quantization_utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/integration_tests/qat_integration_test.py
  tests/unit_tests/phase_delegates_test.py
Labels: size/XL

#243 feature: Add new options for anchorless detect module
  src/super_gradients/recipes/arch_params/yolo_arch_params.yaml
  src/super_gradients/training/models/detection_models/csp_darknet53.py
  src/super_gradients/training/models/detection_models/yolov5_base.py
Labels: size/M

#212 Add yolox fast loss to sg
  src/super_gradients/training/losses/__init__.py
  src/super_gradients/training/losses/all_losses.py
  src/super_gradients/training/losses/yolox_loss.py
Labels: size/L

#246 Sg/readme update
  README.md
Labels: size/S

#247 Set correct defaults
  src/super_gradients/recipes/arch_params/yolo_arch_params.yaml
Labels: size/XS

#245 Make yolo tests run again
  tests/deci_core_unit_test_suite_runner.py
Labels: size/XS

#251 Save student only in ckpt_best for KD
  src/super_gradients/training/kd_model/kd_model.py
  src/super_gradients/training/sg_model/sg_model.py
  tests/unit_tests/kd_model_test.py
Labels: size/M

#236 Feature/sg 155 add logger to upload tensorboard to deci platform
  requirements.txt
  src/super_gradients/common/sg_loggers/__init__.py
  src/super_gradients/common/sg_loggers/deci_platform_sg_logger.py
  src/super_gradients/examples/deci_platform_logger_example/deci_platform_logger_example.py
Labels: size/L

#253 Hotfix/sg 000 fix crowd related bugs
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/metrics/detection_metrics.py
  src/super_gradients/training/transforms/transforms.py
  src/super_gradients/training/utils/detection_utils.py
Labels: size/S

#255 minor badge fix
  README.md
Labels: size/XS

#256 state moved to metrics device
  src/super_gradients/training/metrics/detection_metrics.py
Labels: size/XS

#250 Feature/alg 558 ssd embed anchors
  src/super_gradients/recipes/coco_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/training/losses/ssd_loss.py
  src/super_gradients/training/models/detection_models/ssd.py
  src/super_gradients/training/pretrained_models.py
  src/super_gradients/training/utils/ssd_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#258 fix naming of private functions
  src/super_gradients/training/kd_model/kd_model.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/quantization_utils.py
  tests/end_to_end_tests/trainer_test.py
  tests/unit_tests/strictload_enum_test.py
Labels: size/L

#261 feature/SG-157_support_native_torch_loaders
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/datasets_utils.py
  src/super_gradients/training/sg_model/sg_model.py
Labels: size/L

#260 feature/SG-175 New NMS
  src/super_gradients/training/models/detection_models/yolov5_base.py
  src/super_gradients/training/utils/detection_utils.py
Labels: size/L

#257 allow using an external Optimizer (not initialized outside)
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/optimizer_utils.py
  tests/unit_tests/train_with_intialized_param_args_test.py
Labels: size/S

#264 Sg/readme fix
  README.md
Labels: size/S

#265 Feature/SG-158 fix gt boxes
  src/super_gradients/training/utils/detection_utils.py
Labels: size/S

#263 Fix compute of precision & recall
  src/super_gradients/training/utils/detection_utils.py
Labels: size/S

#248 yolox refactored to use native blocks
  src/super_gradients/training/models/detection_models/csp_darknet53.py
  src/super_gradients/training/models/detection_models/yolov5_base.py
  src/super_gradients/training/utils/export_utils.py
Labels: size/M

#266 fix: Sample max resolution first in multi-scale
  src/super_gradients/training/datasets/datasets_utils.py
Labels: size/S

#269 Hotfix: Run map on CPU
  src/super_gradients/training/metrics/detection_metrics.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/utils/detection_utils.py
Labels: size/M

#204 Feature/sg 131 check env compliance
  .circleci/config.yml
  requirements.txt
  setup.py
  src/super_gradients/__init__.py
  src/super_gradients/common/abstractions/abstract_logger.py
  src/super_gradients/sanity_check/__init__.py
  src/super_gradients/sanity_check/env_sanity_check.py
Labels: size/L

#267 SSD Mobile V1
  src/super_gradients/recipes/anchors/ssd_anchors.yaml
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/coco2017_ssd_mobilenet_v1.yaml
  src/super_gradients/training/models/detection_models/ssd.py
  src/super_gradients/training/pretrained_models.py
  src/super_gradients/training/utils/ssd_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#272 Sg/readme update
  README.md
Labels: size/XS

#270 Support for reading pretrained YoloX models with old blocks
  src/super_gradients/training/models/detection_models/yolov5_base.py
  src/super_gradients/training/utils/checkpoint_utils.py
  tests/unit_tests/yolox_unit_test.py
Labels: size/M

#273 remove anchor generator
  src/super_gradients/examples/legacy/generate_anchors_example.py
  src/super_gradients/training/utils/detection_utils.py
Labels: size/L

#279 feature: Allow custom warmup
  src/super_gradients/training/sg_model/sg_model.py
  tests/unit_tests/lr_warmup_test.py
Labels: size/M

#271 Feature/sg 13 yolox recipes and final fixes
  src/super_gradients/common/factories/callbacks_factory.py
  src/super_gradients/common/factories/datasets_factory.py
  src/super_gradients/recipes/arch_params/yolox_l_arch_params.yaml
  src/super_gradients/recipes/arch_params/yolox_m_arch_params.yaml
  src/super_gradients/recipes/arch_params/yolox_nano_arch_params.yaml
  src/super_gradients/recipes/arch_params/yolox_s_arch_params.yaml
  src/super_gradients/recipes/arch_params/yolox_tiny_arch_params.yaml
  src/super_gradients/recipes/arch_params/yolox_x_arch_params.yaml
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_yolox_dataset_params.yaml
  src/super_gradients/recipes/training_hyperparams/coco2017_yolox_train_params.yaml
  src/super_gradients/recipes/training_hyperparams/default_train_params.yaml
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/models/detection_models/yolov5_base.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/transforms/transforms.py
Labels: size/L

#277 Adapt transforms to work on other DS
  src/super_gradients/training/transforms/__init__.py
  src/super_gradients/training/transforms/transforms.py
Labels: size/L

#280 Updated mAP's in yaml comments, URLs, pretrained model tests
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/training/pretrained_models.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#281 old map out, refs fixed, unused methods removed
  src/super_gradients/training/metrics/detection_metrics.py
  src/super_gradients/training/utils/detection_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/L

#283 refs removed
  tests/integration_tests/pretrained_models_test.py
Labels: size/S

#285 fix: Use not inplace mirror correctly
  src/super_gradients/training/transforms/transforms.py
Labels: size/XS

#239 Add DiceCEEdge loss recipe
  src/super_gradients/recipes/cityscapes_stdc_base.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg75.yaml
  src/super_gradients/recipes/training_hyperparams/cityscapes_stdc_train_params.yaml
  src/super_gradients/training/losses/__init__.py
  src/super_gradients/training/losses/all_losses.py
  src/super_gradients/training/losses/dice_ce_edge_loss.py
  src/super_gradients/training/losses/mask_loss.py
  src/super_gradients/training/pretrained_models.py
  src/super_gradients/training/utils/segmentation_utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/integration_tests/pretrained_models_test.py
  tests/unit_tests/mask_loss_test.py
Labels: size/XL
