Repository Deci-AI/super-gradients, pull requests merged in 2022-03, with the labels that each got.

#139 Update README.md
  README.md
Labels: size/M

#130 Updated & regenrated docs from master
  docs/_modules/super_gradients/training/datasets/segmentation_datasets/coco_segmentation.html
  docs/_sources/welcome.md.txt
  docs/index.html
  docs/objects.inv
  docs/py-modindex.html
  docs/searchindex.js
  docs/welcome.html
  documentation/source/welcome.md
Labels: size/L

#143 default gpu mode updated
  src/super_gradients/training/sg_model/sg_model.py
Labels: size/XS

#147 add configurable img_mean, img_std + lint issues
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
Labels: size/S

#132 Add dice loss tests
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/dice_loss_test.py
Labels: size/L

#152 Sg/readme branch
  README.md
Labels: size/M

#149 Feature/sg 75 refactor train from recipe
  src/super_gradients/__init__.py
  src/super_gradients/recipes/cifar10_resnet.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
  src/super_gradients/recipes/coco2017_yolov5.yaml
  src/super_gradients/recipes/coco_segmentation_shelfnet_lw.yaml
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/imagenet_mobilenetv2.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3.yaml
  src/super_gradients/recipes/imagenet_regnetY.yaml
  src/super_gradients/recipes/imagenet_repvgg.yaml
  src/super_gradients/recipes/imagenet_resnet50.yaml
Labels: size/M

#153 Sg/readme branch
  README.md
Labels: size/S

#154 Add criterion to context before train starts
  src/super_gradients/training/sg_model/sg_model.py
Labels: size/XS

#157 Feature/sg 71 kd module
  docs/_sources/user_guide.md.txt
  docs/user_guide.html
  documentation/source/user_guide.md
  src/super_gradients/examples/cifar10_external_optimizer/cifar10_external_optimizer_example.py
  src/super_gradients/examples/ddrnet_cityscapes/ddrnet_classification_example.py
  src/super_gradients/examples/early_stop/early_stop_example.py
  src/super_gradients/examples/legacy/darknet53_example.py
  src/super_gradients/examples/legacy/imagenet_resnet_ddp/distributed_training_imagenet.py
  src/super_gradients/examples/legacy/yolo_v3_coco.py
  src/super_gradients/examples/legacy/yolo_v3_subclass.py
  src/super_gradients/examples/user_guide_walkthrough_example/train.py
  src/super_gradients/training/kd_model/__init__.py
  src/super_gradients/training/kd_model/kd_model.py
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/kd_modules/__init__.py
  src/super_gradients/training/models/kd_modules/kd_module.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/trainer.py
  src/super_gradients/training/utils/sg_model_utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/end_to_end_tests/cifar10_trainer_test.py
  tests/end_to_end_tests/external_dataset_e2e.py
  tests/end_to_end_tests/trainer_test.py
  tests/integration_tests/lr_test.py
  tests/test-data-interface.py
  tests/unit_tests/dataset_statistics_test.py
  tests/unit_tests/detection_utils_test.py
  tests/unit_tests/early_stop_test.py
  tests/unit_tests/factories_test.py
  tests/unit_tests/kd_module_test.py
  tests/unit_tests/load_checkpoint_from_direct_path_test.py
  tests/unit_tests/load_ema_ckpt_test.py
  tests/unit_tests/phase_context_test.py
  tests/unit_tests/save_ckpt_test.py
  tests/unit_tests/strictload_enum_test.py
  tests/unit_tests/test_without_train_test.py
  tests/unit_tests/train_logging_test.py
  tests/unit_tests/train_with_intialized_param_args_test.py
  tests/unit_tests/train_with_precise_bn_test.py
Labels: size/XL

#156 minor readme change
  README.md
Labels: size/S

#160 yaml files fixed
  src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
  src/super_gradients/recipes/coco2017_yolov5.yaml
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/imagenet_mobilenetv2.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3.yaml
  src/super_gradients/recipes/imagenet_regnetY.yaml
  src/super_gradients/recipes/imagenet_repvgg.yaml
  src/super_gradients/recipes/imagenet_resnet50.yaml
Labels: size/S

#161 fix stdc context conversion
  src/super_gradients/training/models/segmentation_models/stdc.py
Labels: size/XS

#138 MobileNet input channels
  src/super_gradients/training/models/classification_models/mobilenetv2.py
  src/super_gradients/training/models/classification_models/mobilenetv3.py
Labels: size/M

#164 Sg/architectures_supported
  README.md
Labels: size/M
