Repository Deci-AI/super-gradients, pull requests merged in 2022-10, with the labels that each got.

#413 Replace torch.tensor by my_tensor.clone().detach()
  src/super_gradients/training/utils/distributed_training_utils.py
Labels: size/XS

#409 FIX: Rename memory_cached
  src/super_gradients/training/sg_trainer/sg_trainer.py
  src/super_gradients/training/utils/distributed_training_utils.py
Labels: size/S

#418 Improve cross-platform compatibility when parsing a readme description
  setup.py
Labels: size/XS

#423 added useful hydra resolvers with tests
  src/super_gradients/common/environment/env_helpers.py
  tests/unit_tests/hydra_resolvers_test.py
Labels: size/M

#424 fix PR 413
  src/super_gradients/training/utils/distributed_training_utils.py
Labels: size/XS

#425 support custom STDC
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/segmentation_models/stdc.py
Labels: size/XS

#426 Rename shelfnet classes_num param
  src/super_gradients/training/models/segmentation_models/shelfnet.py
  tests/unit_tests/shelfnet_unit_test.py
Labels: size/S

#405 Feature/sg 292 update register model
  src/super_gradients/common/registry/README.md
  src/super_gradients/training/models/model_factory.py
  src/super_gradients/training/utils/sg_trainer_utils.py
  src/super_gradients/training/utils/utils.py
  tests/unit_tests/test_without_train_test.py
Labels: size/L

#415 Feature/sg 328 move object names
  src/super_gradients/__init__.py
  src/super_gradients/common/object_names.py
  src/super_gradients/training/datasets/samplers/all_samplers.py
  src/super_gradients/training/losses/all_losses.py
  src/super_gradients/training/metrics/all_metrics.py
  src/super_gradients/training/models/__init__.py
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/model_factory.py
  src/super_gradients/training/transforms/all_transforms.py
  src/super_gradients/training/utils/callbacks/all_callbacks.py
  src/super_gradients/training/utils/optimizers/all_optimizers.py
Labels: size/L

#412 Mute logging for subprocesses
  src/super_gradients/common/abstractions/abstract_logger.py
  src/super_gradients/common/auto_logging/auto_logger.py
  src/super_gradients/common/environment/environment_config.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
  src/super_gradients/training/utils/distributed_training_utils.py
  src/super_gradients/training/utils/sg_trainer_utils.py
Labels: size/M

#417 Update requirements.txt
  requirements.txt
Labels: size/XS

#411 added support for any iou threshold (float instead of enum).
  src/super_gradients/common/object_names.py
  src/super_gradients/training/metrics/__init__.py
  src/super_gradients/training/metrics/all_metrics.py
  src/super_gradients/training/metrics/detection_metrics.py
Labels: size/L

#422 Improve Windows platform support.
  src/super_gradients/common/plugins/deci_client.py
  src/super_gradients/training/dataloaders/dataloaders.py
  src/super_gradients/training/training_hyperparams/training_hyperparams.py
  src/super_gradients/training/utils/hydra_utils.py
Labels: size/XL

#428 Feature/sg 371 move sync bn to training params
  src/super_gradients/recipes/arch_params/default_arch_params.yaml
  src/super_gradients/recipes/arch_params/efficientnet_arch_params.yaml
  src/super_gradients/recipes/arch_params/mobilenet_v2_arch_params.yaml
  src/super_gradients/recipes/arch_params/mobilenet_v3_arch_params.yaml
  src/super_gradients/recipes/arch_params/regnetY_arch_params.yaml
  src/super_gradients/recipes/arch_params/repvgg_arch_params.yaml
  src/super_gradients/recipes/arch_params/resnet18_cifar_arch_params.yaml
  src/super_gradients/recipes/arch_params/resnet50_arch_params.yaml
  src/super_gradients/recipes/arch_params/shelfnet34_lw_arch_params.yaml
  src/super_gradients/recipes/arch_params/vit_base_arch_params.yaml
  src/super_gradients/recipes/arch_params/yolo_arch_params.yaml
  src/super_gradients/recipes/cityscapes_ddrnet.yaml
  src/super_gradients/recipes/cityscapes_pplite_seg50.yaml
  src/super_gradients/recipes/cityscapes_pplite_seg75.yaml
  src/super_gradients/recipes/cityscapes_regseg48.yaml
  src/super_gradients/recipes/cityscapes_stdc_base.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg75.yaml
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/imagenet_resnet50_kd.yaml
  src/super_gradients/recipes/training_hyperparams/default_train_params.yaml
  src/super_gradients/training/params.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/M

#429 ddp logic changed
  src/super_gradients/training/utils/distributed_training_utils.py
Labels: size/XS

#431 fix: Load weights from the platform
  src/super_gradients/training/models/model_factory.py
Labels: size/S

#438 Feature/sg 344 refactor modules
  src/super_gradients/modules/__init__.py
  src/super_gradients/modules/conv_bn_act_block.py
  src/super_gradients/modules/repvgg_block.py
  src/super_gradients/modules/se_blocks.py
  src/super_gradients/training/models/classification_models/repvgg.py
  src/super_gradients/training/models/segmentation_models/ppliteseg.py
  src/super_gradients/training/models/segmentation_models/regseg.py
  src/super_gradients/training/models/segmentation_models/stdc.py
  src/super_gradients/training/utils/module_utils.py
  tests/unit_tests/conv_bn_relu_test.py
Labels: size/XL

#439 Feature-177/Add message with effective batch size when training
  src/super_gradients/training/sg_trainer/sg_trainer.py
  src/super_gradients/training/utils/sg_trainer_utils.py
Labels: size/S

#443 Feature/SG 344 - ActivationsTypeFactory
  src/super_gradients/common/factories/__init__.py
  src/super_gradients/common/factories/activations_type_factory.py
  src/super_gradients/training/utils/activations_utils.py
  tests/unit_tests/factories_test.py
Labels: size/L
