Repository Deci-AI/super-gradients, pull requests merged in 2022-09, with the labels that each got.

#343 feature/sg-223-segmentation-dataset-refactor
  src/super_gradients/common/factories/transforms_factory.py
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/segmentation_datasets/segmentation_dataset.py
Labels: size/L

#347 Feature/sg 252 coco dataset refactor
  src/super_gradients/recipes/coco_segmentation_shelfnet_lw.yaml
  src/super_gradients/recipes/training_hyperparams/coco_segmentation_shelfnet_lw_train_params.yaml
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/segmentation_datasets/coco_segmentation.py
Labels: size/M

#348 Feature/sg 252 coco seg new dataset params
  src/super_gradients/recipes/coco_segmentation_shelfnet_lw.yaml
  src/super_gradients/recipes/dataset_params/coco_segmentation_dataset_params.yaml
  src/super_gradients/training/dataloaders/dataloader_factory.py
  src/super_gradients/training/datasets/dataset_interfaces/dataset_interface.py
  src/super_gradients/training/datasets/segmentation_datasets/coco_segmentation.py
  tests/unit_tests/cityscapes_dataset_test.py
  tests/unit_tests/coco_segmentation_dataset_test.py
Labels: size/L

#334 Feature/sg 216 refactor seg aug dataloader
  src/super_gradients/recipes/dataset_params/pascal_aug_segmentation_dataset_params.yaml
  src/super_gradients/training/dataloaders/dataloader_factory.py
  tests/unit_tests/datalaoder_factory_test.py
Labels: size/M

#333 add pascalVOC segmentation to dataloader
  src/super_gradients/recipes/dataset_params/pascal_voc_segmentation_dataset_params.yaml
  src/super_gradients/training/dataloaders/dataloader_factory.py
  tests/unit_tests/datalaoder_factory_test.py
Labels: size/M

#338 Feature/sg 220 refactor supervisely dataset
  src/super_gradients/common/factories/transforms_factory.py
  src/super_gradients/recipes/dataset_params/supervisely_persons_dataset_params.yaml
  src/super_gradients/training/dataloaders/dataloader_factory.py
  src/super_gradients/training/datasets/__init__.py
  tests/unit_tests/datalaoder_factory_test.py
Labels: size/M

#332 feature/SG-220_refactor_pascal_detection_dataset_interface
  src/super_gradients/recipes/dataset_params/pascal_voc_detection_dataset_params.yaml
  src/super_gradients/training/dataloaders/dataloader_factory.py
  src/super_gradients/training/datasets/detection_datasets/pascal_voc_detection.py
  tests/unit_tests/datalaoder_factory_test.py
Labels: size/L

#352 Segmentation dataset cache fix
  src/super_gradients/training/datasets/segmentation_datasets/cityscape_segmentation.py
  src/super_gradients/training/datasets/segmentation_datasets/coco_segmentation.py
  src/super_gradients/training/datasets/segmentation_datasets/supervisely_persons_segmentation.py
Labels: size/XS

#349 PPLiteSeg modules
  src/super_gradients/common/__init__.py
  src/super_gradients/common/data_types/__init__.py
  src/super_gradients/common/data_types/enum/__init__.py
  src/super_gradients/common/data_types/enum/upsample_mode.py
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/segmentation_models/ppliteseg.py
  src/super_gradients/training/models/segmentation_models/segmentation_module.py
  src/super_gradients/training/pretrained_models.py
  src/super_gradients/training/utils/module_utils.py
  tests/integration_tests/pretrained_models_test.py
Labels: size/XL

#353 fix wrong name capitalization
  src/super_gradients/training/models/detection_models/yolo_base.py
  src/super_gradients/training/models/detection_models/yolox.py
Labels: size/M

#354 added AnyNetX to the ARCHITECTURES
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/classification_models/regnet.py
Labels: size/S

#355 support anynet backbone
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/detection_models/yolo_base.py
  src/super_gradients/training/models/detection_models/yolox.py
Labels: size/M

#360 get training_params
  src/super_gradients/training/dataloaders/dataloader_factory.py
  src/super_gradients/training/training_hyperparams/__init__.py
  src/super_gradients/training/training_hyperparams/training_hyperparams.py
  src/super_gradients/training/utils/utils.py
  tests/deci_core_unit_test_suite_runner.py
  tests/unit_tests/__init__.py
  tests/unit_tests/training_params_factory_test.py
Labels: size/L

#361 Update README.md
  README.md
Labels: size/XS

#362 Update README.md
  README.md
Labels: size/XS

#350 Launch DDP with script
  README.md
  src/super_gradients/common/environment/env_helpers.py
  src/super_gradients/common/environment/environment_config.py
  src/super_gradients/examples/train_from_kd_recipe_example/train_from_kd_recipe.py
  src/super_gradients/examples/train_from_recipe_example/train_from_recipe.py
  src/super_gradients/recipes/cityscapes_ddrnet.yaml
  src/super_gradients/recipes/cityscapes_regseg48.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg75.yaml
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/recipes/coco_segmentation_shelfnet_lw.yaml
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/imagenet_mobilenetv2.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_base.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_large.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_small.yaml
  src/super_gradients/recipes/imagenet_repvgg.yaml
  src/super_gradients/recipes/imagenet_resnet50.yaml
  src/super_gradients/recipes/imagenet_resnet50_kd.yaml
  src/super_gradients/recipes/imagenet_vit_base.yaml
  src/super_gradients/recipes/imagenet_vit_large.yaml
  src/super_gradients/training/exceptions/sg_trainer_exceptions.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
  src/super_gradients/training/utils/distributed_training_utils.py
Labels: size/L

#367 fix: Request correct hydra-core
  requirements.txt
Labels: size/XS

#370 fix: Plot detection in RGB
  src/super_gradients/training/datasets/detection_datasets/detection_dataset.py
Labels: size/XS

#368 fix: Change model's num_classes after replace_head
  src/super_gradients/training/models/detection_models/yolo_base.py
Labels: size/XS

#369 feature: Allow to see default params
  src/super_gradients/training/dataloaders/dataloaders.py
Labels: size/S

#373 Fixes for segmentation notebooks
  src/super_gradients/recipes/dataset_params/supervisely_persons_dataset_params.yaml
  src/super_gradients/training/models/segmentation_models/ppliteseg.py
  src/super_gradients/training/models/segmentation_models/stdc.py
Labels: size/S

#377 Added tutorial on recipes
  tutorials/what_are_recipes_and_how_to_use.ipynb
Labels: size/XL

#366 Feature/sg 296 rename parameter
  src/super_gradients/training/models/model_factory.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
  tests/integration_tests/conversion_callback_test.py
Labels: size/S

#310 Feature/sg 221 reproduce yolox fastloss
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/recipes/dataset_params/coco_detection_dataset_params.yaml
  src/super_gradients/recipes/training_hyperparams/coco2017_yolox_train_params.yaml
  src/super_gradients/training/losses/__init__.py
  src/super_gradients/training/losses/all_losses.py
  src/super_gradients/training/losses/yolox_loss.py
Labels: size/L

#363 rename register to register_model (to support future registrators)
  src/super_gradients/training/models/model_registry.py
  src/super_gradients/training/models/user_models/README.md
  tests/unit_tests/model_registry_test.py
Labels: size/S

#379 SgModel and KDModel removal
  documentation/source/welcome.md
  src/super_gradients/__init__.py
  src/super_gradients/examples/regseg_transfer_learning_example/regseg_transfer_learning_example.py
  src/super_gradients/training/__init__.py
  src/super_gradients/training/kd_model/__init__.py
  src/super_gradients/training/kd_model/kd_model.py
  src/super_gradients/training/models/segmentation_models/segmentation_module.py
  src/super_gradients/training/sg_model/__init__.py
  src/super_gradients/training/sg_model/sg_model.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
Labels: size/M

#371 Hotfix/sg 298 ckpt dir not found
  src/super_gradients/common/environment/environment_config.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
Labels: size/S

#364 build_model refs replaced
  src/super_gradients/examples/deci_lab_export_example/deci_lab_export_example.py
  src/super_gradients/examples/regseg_transfer_learning_example/regseg_transfer_learning_example.py
  src/super_gradients/training/dataloaders/dataloaders.py
  src/super_gradients/training/kd_trainer/kd_trainer.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
  src/super_gradients/training/utils/quantization_utils.py
  tests/unit_tests/phase_delegates_test.py
Labels: size/L

#391 Padding value is now configurable via yaml
  src/super_gradients/training/transforms/transforms.py
Labels: size/XS

#388 bugfix - change default dict to be not mutuble
  src/super_gradients/training/models/model_factory.py
Labels: size/XS

#395 fix wrong func names
  src/super_gradients/common/plugins/deci_client.py
Labels: size/XS

#393 Augment HSV will allow configuring bgr_channels in case there are oth…
  src/super_gradients/training/transforms/transforms.py
Labels: size/S

#396 Trainer constructor cleanup
  src/super_gradients/examples/resnet_qat/resnet_qat_example.py
  src/super_gradients/recipes/cifar10_resnet.yaml
  src/super_gradients/recipes/cityscapes_ddrnet.yaml
  src/super_gradients/recipes/cityscapes_regseg48.yaml
  src/super_gradients/recipes/cityscapes_stdc_base.yaml
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/recipes/coco_segmentation_shelfnet_lw.yaml
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/imagenet_mobilenetv2.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_base.yaml
  src/super_gradients/recipes/imagenet_regnetY.yaml
  src/super_gradients/recipes/imagenet_repvgg.yaml
  src/super_gradients/recipes/imagenet_resnet50.yaml
  src/super_gradients/recipes/imagenet_resnet50_kd.yaml
  src/super_gradients/recipes/imagenet_vit_base.yaml
  src/super_gradients/recipes/training_hyperparams/default_train_params.yaml
  src/super_gradients/training/kd_trainer/kd_trainer.py
  src/super_gradients/training/params.py
  src/super_gradients/training/sg_trainer/sg_trainer.py
  src/super_gradients/training/utils/checkpoint_utils.py
  src/super_gradients/training/utils/weight_averaging_utils.py
  tests/end_to_end_tests/cifar_trainer_test.py
  tests/end_to_end_tests/trainer_test.py
  tests/integration_tests/conversion_callback_test.py
  tests/integration_tests/deci_lab_export_test.py
  tests/integration_tests/ema_train_integration_test.py
  tests/integration_tests/lr_test.py
  tests/integration_tests/pretrained_models_test.py
  tests/integration_tests/qat_integration_test.py
  tests/unit_tests/dataset_statistics_test.py
  tests/unit_tests/detection_utils_test.py
  tests/unit_tests/early_stop_test.py
  tests/unit_tests/factories_test.py
  tests/unit_tests/initialize_with_dataloaders_test.py
  tests/unit_tests/load_ema_ckpt_test.py
  tests/unit_tests/lr_cooldown_test.py
  tests/unit_tests/lr_warmup_test.py
  tests/unit_tests/phase_context_test.py
  tests/unit_tests/phase_delegates_test.py
  tests/unit_tests/pretrained_models_unit_test.py
  tests/unit_tests/save_ckpt_test.py
  tests/unit_tests/strictload_enum_test.py
  tests/unit_tests/test_without_train_test.py
  tests/unit_tests/train_logging_test.py
  tests/unit_tests/train_with_intialized_param_args_test.py
  tests/unit_tests/train_with_precise_bn_test.py
  tests/unit_tests/update_param_groups_unit_test.py
  tutorials/what_are_recipes_and_how_to_use.ipynb
Labels: size/L

#398 Sg/new readme
  README.md
  docs/assets/SG_img/Classification 1500x900.png
  docs/assets/SG_img/Classification.png
  docs/assets/SG_img/Classification@2x.png
  docs/assets/SG_img/Computer_Vision_Models_Pretrained_Checkpoints.md
  docs/assets/SG_img/Implemented Model Architectures.md
  docs/assets/SG_img/Object Detection.png
  docs/assets/SG_img/Object Detection@2x.png
  docs/assets/SG_img/Object detection 1500X900.png
  docs/assets/SG_img/Segmentation 1500x900 .png
  docs/assets/SG_img/Semantic Segmentation.png
  docs/assets/SG_img/Semantic Segmentation@2x.png
  docs/assets/SG_img/Training_Recipes.md
Labels: size/XXL

#394 Add eval recipe
  src/super_gradients/common/environment/env_helpers.py
  src/super_gradients/examples/evaluate_checkpoint_example/__init__.py
  src/super_gradients/examples/evaluate_checkpoint_example/evaluate_checkpoint.py
  src/super_gradients/examples/evaluate_from_recipe_example/__init__.py
  src/super_gradients/examples/evaluate_from_recipe_example/evaluate_from_recipe.py
  src/super_gradients/examples/resume_experiment_example/__init__.py
  src/super_gradients/examples/resume_experiment_example/resume_experiment.py
  src/super_gradients/recipes/cifar10_resnet.yaml
  src/super_gradients/recipes/cityscapes_ddrnet.yaml
  src/super_gradients/recipes/cityscapes_regseg48.yaml
  src/super_gradients/recipes/cityscapes_stdc_base.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg50.yaml
  src/super_gradients/recipes/cityscapes_stdc_seg75.yaml
  src/super_gradients/recipes/coco2017_ssd_lite_mobilenet_v2.yaml
  src/super_gradients/recipes/coco2017_yolox.yaml
  src/super_gradients/recipes/coco_segmentation_shelfnet_lw.yaml
  src/super_gradients/recipes/imagenet_efficientnet.yaml
  src/super_gradients/recipes/imagenet_mobilenetv2.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_base.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_large.yaml
  src/super_gradients/recipes/imagenet_mobilenetv3_small.yaml
  src/super_gradients/recipes/imagenet_regnetY.yaml
  src/super_gradients/recipes/imagenet_repvgg.yaml
  src/super_gradients/recipes/imagenet_resnet50.yaml
  src/super_gradients/recipes/imagenet_resnet50_kd.yaml
  src/super_gradients/recipes/imagenet_vit_base.yaml
  src/super_gradients/recipes/imagenet_vit_large.yaml
  src/super_gradients/training/sg_trainer/sg_trainer.py
  src/super_gradients/training/utils/checkpoint_utils.py
  src/super_gradients/training/utils/hydra_utils.py
  src/super_gradients/training/utils/sg_trainer_utils.py
Labels: size/L

#344 Feature/sg 255 add class for supported strings
  src/super_gradients/__init__.py
  src/super_gradients/common/factories/__init__.py
  src/super_gradients/common/factories/callbacks_factory.py
  src/super_gradients/common/factories/metrics_factory.py
  src/super_gradients/common/factories/optimizers_type_factory.py
  src/super_gradients/common/factories/samplers_factory.py
  src/super_gradients/common/factories/transforms_factory.py
  src/super_gradients/examples/regseg_transfer_learning_example/regseg_transfer_learning_example.py
  src/super_gradients/recipes/dataset_params/cityscapes_ddrnet_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/cityscapes_regseg48_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/cityscapes_stdc_seg50_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/cityscapes_stdc_seg75_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/coco_segmentation_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/pascal_aug_segmentation_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/pascal_voc_segmentation_dataset_params.yaml
  src/super_gradients/recipes/dataset_params/supervisely_persons_dataset_params.yaml
  src/super_gradients/training/datasets/all_datasets.py
  src/super_gradients/training/datasets/samplers/__init__.py
  src/super_gradients/training/datasets/samplers/all_samplers.py
  src/super_gradients/training/losses/__init__.py
  src/super_gradients/training/losses/all_losses.py
  src/super_gradients/training/metrics/__init__.py
  src/super_gradients/training/metrics/all_metrics.py
  src/super_gradients/training/models/__init__.py
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/object_names.py
  src/super_gradients/training/transforms/__init__.py
  src/super_gradients/training/transforms/all_transforms.py
  src/super_gradients/training/transforms/transforms.py
  src/super_gradients/training/utils/callbacks.py
  src/super_gradients/training/utils/callbacks/__init__.py
  src/super_gradients/training/utils/callbacks/all_callbacks.py
  src/super_gradients/training/utils/callbacks/callbacks.py
  src/super_gradients/training/utils/optimizers/__init__.py
  src/super_gradients/training/utils/optimizers/all_optimizers.py
  tests/unit_tests/segmentation_transforms_test.py
Labels: size/XXL

#400 Generalize register_model
  src/super_gradients/training/models/model_registry.py
  src/super_gradients/training/models/user_models/README.md
  src/super_gradients/training/utils/registry.py
  tests/unit_tests/model_registry_test.py
Labels: size/M

#402 return model and results from the train_from_config function
  src/super_gradients/training/sg_trainer/sg_trainer.py
Labels: size/S

#403 Add register metric
  src/super_gradients/common/registry/README.md
  src/super_gradients/common/registry/__init__.py
  src/super_gradients/common/registry/registry.py
  tests/unit_tests/registry_test.py
Labels: size/L

#399 Feature/sg 326 replace function with class in architectures
  src/super_gradients/training/models/all_architectures.py
  src/super_gradients/training/models/classification_models/beit.py
  src/super_gradients/training/models/classification_models/densenet.py
  src/super_gradients/training/models/classification_models/efficientnet.py
  src/super_gradients/training/models/classification_models/googlenet.py
  src/super_gradients/training/models/classification_models/mobilenetv2.py
  src/super_gradients/training/models/classification_models/mobilenetv3.py
  src/super_gradients/training/models/classification_models/resnet.py
  src/super_gradients/training/models/classification_models/resnext.py
  src/super_gradients/training/models/classification_models/vit.py
  tests/unit_tests/all_architectures_test.py
Labels: size/XL

#406 Feature/SG 293 - Add register loss
  src/super_gradients/common/registry/README.md
  src/super_gradients/common/registry/__init__.py
  src/super_gradients/common/registry/registry.py
  tests/unit_tests/registry_test.py
Labels: size/M

#408 Fix load_backbone
  src/super_gradients/training/models/model_factory.py
  src/super_gradients/training/utils/checkpoint_utils.py
Labels: size/XS

#404 Sg/readme update img
  README.md
  docs/assets/SG_img/Classification@2xDark.png
  docs/assets/SG_img/Object Detection@2xDark.png
  docs/assets/SG_img/SG - Horizontal Glow 2.png
  docs/assets/SG_img/SG - Horizontal Glow.png
  docs/assets/SG_img/Semantic Segmentation@2xDark.png
  src/super_gradients/recipes/Training_Recipes.md
  src/super_gradients/training/Computer_Vision_Models_Pretrained_Checkpoints.md
  src/super_gradients/training/models/Implemented Model Architectures.md
Labels: size/M

#407 PPLiteSeg recipes
  src/super_gradients/recipes/cityscapes_pplite_seg50.yaml
  src/super_gradients/recipes/cityscapes_pplite_seg75.yaml
  src/super_gradients/recipes/dataset_params/cityscapes_ppliteseg_seg75_dataset_params.yaml
  src/super_gradients/training/losses/dice_ce_edge_loss.py
Labels: size/L

#410 Remove AWS env check
  src/super_gradients/common/environment/__init__.py
  src/super_gradients/common/environment/environment_config.py
Labels: size/S
